### ISSUE TITLE
fis-plus 环境下不好使，编译后未添加 define 头

### ISSUE THREAD

**Issue by sophister** [fouber/fis-parser-react#2]
在 `fis-plus` 下，按照说明安装并修改 `fis-conf.js`，之后用  `fisp release -pcmd remote` 发布到测试机上，发现原来  `.jsx` 的文件，内容已经被转换成JS，但是单个JS内，并没有加上  `define(xxx)` 的头，导致在 `require` 的时候找不到模块

**Comment by fouber** [comment]
加define头是另外一个插件的工作，在fis-plus中应该额外配置那个插件给jsx文件加define，fis-parser-react只是负责把jsx编译成js文件而已

**Comment by sophister** [comment]
``` javascript
fis.config.set('roadmap.ext.jsx', 'js');        //*.jsx are exactly treat as *.js 
```

这个是让jsx作为JS来处理，默认不是会对JS加上  define 头的么

**Comment by fouber** [comment]
@sophister 

这个配置是告诉fis系统，把jsx后缀的文件当做js产出和处理。然而并不是所有的js都加define的，真正决定一个js是否加define是文件对象的isMod属性。所以你的配置还需要再追加：

``` js
fis.config.set('roadmap.path', [
    {
        reg: 'modules/**.jsx',    //modules目录下的所有jsx文件（假设你的模块化目录是modules）
        isMod: true               //是模块化的资源
    }
]);
```

**Comment by sophister** [comment]
@fouber  云龙果然给力啊
